#!/bin/sh
name=binutils-host
version=2.43.1
tarball_url="https://fosszone.csd.auth.gr/gnu/binutils/binutils-${version}.tar.xz"
tarball_blake2b="c4cd765cea326cd00b5cfe306e2937d820603b42f07a714ceb1349d36ddba0d45c3e125599dadf290d97954035c381781067155600ed87066e494cb9c4b34b45"
source_hostdeps="autoconf-2.69 automake libtool pkg-config"
hostdeps="autoconf-2.69 automake libtool pkg-config"
imagedeps="build-essential"

prepare() {
    autotools_recursive_regen -I"$(realpath ./config)"

    cp -pv /usr/local/share/libtool/build-aux/{config.sub,config.guess,install-sh} libiberty/
}

