#!/bin/sh
name=mlibc
version=b4fb75b3379762d006e7d9b98fd739778e2d3a21
source_method=tarball
tarball_url="https://github.com/managarm/mlibc/archive/${version}.tar.gz"
tarball_sha512="fa5c10847954fea6bd5de4da387b95ebf09abb922f1072e638b91de7338127417bb80b4a97ab570cb3ca94f1fec0990f4b55126d97976d9718dd57b3b9fb2410"

prepare() {
    cp -r /base_dir/mlibc-salernos/sysdeps "${source_dir}/sysdeps/salernos"
    cp -r /base_dir/mlibc-salernos/abi "${source_dir}/abis/salernos"
    for file in /base_dir/sources/mlibc/abis/salernos/*; do
        ln -s "$file" "${source_dir}/sysdeps/salernos/include/abi-bits"
    done
}
