#! /bin/sh

name=base
skip_pkg_check=yes
version=0.0
revision=3
deps="bash binutils bzip2 coreutils diffutils epoch findutils
gawk gcc gmp grep gzip less make mpc mpfr nano ncurses pcre2
readline sed tar tzdata xz zlib zstd metalog cronie man-db
texinfo xbps cal"
