#!/bin/sh
name=freestnd-c-hdrs
version=87956bbcad0e1934e708223913be53131311342d
revision=1
imagedeps="rsync"
git_url="https://codeberg.org/osdev/freestnd-c-hdrs"
commit=${version}

build() {
    rsync -av --exclude='.git' "${source_dir}"/. .
}

package() {
    DESTDIR="${dest_dir}" PREFIX="${prefix}" make install
}
