#!/bin/sh

name=fresh
version=0.0.2
skip_pkg_check=yes
revision=1
git_url="https://github.com/Alessandro-Salerno/fresh"
commit="173c46fa05251afd5ebe36899f8d5dc78a03f3b9"
imagedeps="build-essential curl nasm"
hostdeps="gcc"

build() {
    cp -pr "${source_dir}"/* .
    make -j${parallelism}
}

package() {
    mkdir -p "${dest_dir}"
    cp ./bin/* "${dest_dir}"
}
