#!/bin/sh

name=fresh
version=0.0.2
skip_pkg_check=yes
revision=1
git_url="https://github.com/Alessandro-Salerno/fresh"
commit="ef1ba339869b0c1873dca12dc19c97d77406cf89"
imagedeps="build-essential curl nasm"

build() {
    cp -pr "${source_dir}"/* .
    make -j${parallelism}
}

package() {
    mkdir -p "${dest_dir}/initrd_root"
    cp ./bin/* "${dest_dir}/initrd_root"
}
