#!/bin/sh

name=init
version=0.0.1
skip_pkg_check=yes
revision=1
source_dir="init"
imagedeps="git build-essential"
hostdeps="gcc binutils libgcc-binaries"
deps="mlibc-headers mlibc freestnd-c-hdrs freestnd-cxx-hdrs libgcc"

build() {
    cp -pr "${source_dir}"/* .
    make CC=x86_64-salernos-mlibc-gcc LD=x86_64-salernos-mlibc-gcc
}

package() {
    mkdir -p "${dest_dir}/boot"
    cp ./bin/init "${dest_dir}/boot/init"
}
