#!/bin/sh

name=kernel
version=0.2.2
skip_pkg_check=yes
revision=1
source_dir="kernel"
imagedeps="build-essential curl nasm"

build() {
    cp -pr "${source_dir}"/* .
    make -j${parallelism}
}

package() {
    mkdir -p "${dest_dir}/boot"
    cp ./bin/vmsalernos "${dest_dir}/boot"
}
