#!/bin/sh

name=mtm
version=1.2.1
skip_pkg_check=yes
revision=1
git_url="https://github.com/deadpixi/mtm"
commit="b346b86208007762d8f6b006722e4f0113446820"
imagedeps="git build-essential"
hostdeps="gcc binutils libgcc-binaries"
deps="mlibc-headers mlibc freestnd-c-hdrs freestnd-cxx-hdrs libgcc ncurses"

build() {
    cp -pr "${source_dir}"/* .
    make CC=${OS_TRIPLET}-gcc LIBS="-lutil -lncursesw -ltinfow"
}

package() {
    mkdir -p "${dest_dir}"
    make install DESTDIR="${dest_dir}"
}