#!/bin/sh
name=sha256
version=0.0.1
skip_pkg_check=yes
revision=1
git_url="https://github.com/EddieEldridge/SHA256-in-C"
allow_network="yes"
commit="8127df56953e752577dfde487d3da89653a349d2"
imagedeps="git build-essential"
hostdeps="gcc binutils libgcc-binaries"
deps="mlibc-headers mlibc freestnd-c-hdrs freestnd-cxx-hdrs libgcc"

build() {
    cp -pr "${source_dir}"/* .
    x86_64-salernos-mlibc-gcc SHA256.c -std=c99 -o sha256sum
}

package() {
    mkdir -p "${dest_dir}"
    cp ./sha256sum "${dest_dir}"
}
