#! /bin/sh

name=tmux
version=a6588d691856ab329772c16989172644e4c9f34e
revision=1
git_url="https://github.com/tmux/tmux"
source_hostdeps="automake autoconf libtool pkg-config"
hostdeps="gcc pkg-config libtool autoconf automake libtool"
deps="core-libs ncurses libevent"
commit=${version}


prepare() {
    ./autogen.sh
}

configure() {
    autotools_configure 
}

build() {
    make -j${parallelism}
}

package() {
    # TODO: update it
    mkdir "${dest_dir}${prefix}"/bin/
    cp -v tmux "${dest_dir}${prefix}"/bin/
    post_package_strip
}

