#!/bin/sh

name=tte
version=0.1.1
skip_pkg_check=yes
revision=1
git_url="https://github.com/GrenderG/tte"
commit="80e105d38582319efc02039121dcd742c12964d8"
imagedeps="git build-essential"
hostdeps="gcc binutils libgcc-binaries"
deps="mlibc-headers mlibc freestnd-c-hdrs freestnd-cxx-hdrs libgcc"

build() {
    cp -pr "${source_dir}"/* .
    make tte CC=x86_64-salernos-mlibc-gcc
}

package() {
    mkdir -p "${dest_dir}"
    cp ./tte "${dest_dir}"
}
