#! /bin/sh

name=twm
version=1.0.12
revision=1
tarball_url="https://www.x.org/pub/individual/app/twm-${version}.tar.xz"
tarball_sha512="f3d68df7e06516f6b74f19181efcfd9db2479c8ea0c72c3a6ed0dc1b222405b40d81a2dea17b662955e0c1783e87d0d3eb067c3b6e7c6eed8c0d38d03d362260"
source_hostdeps="automake autoconf libtool pkg-config"
source_deps="gettext xorg-util-macros xtrans"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs libx11 xorg-server xorg-xsetroot xorg-util-macros"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
    post_package_strip
}
